### Практическое задание. Урок 3.

#### 2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], dtype = np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [3]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [4]:
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])

In [5]:
X_st

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  2.        ,  1.        ,  3.        ,
         0.        ,  5.        , 10.        ,  1.        ,  2.        ],
       [-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
        -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735],
       [ 1.        ,  1.        ,  2.        ,  1.        ,  2.        ,
         1.        ,  3.        ,  3.        ,  1.        ,  2.        ]])

In [6]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [7]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [8]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
    if i % (iterations / 10) == 0:
        print(i, W, err)
    return W, err

In [9]:
def best_param(iterations, alphas):
    best = [999, 0, 0]
    for iteration in iterations:
        for alfa in alphas:
            print(f'iteration: {iteration}, alfa: {alfa}')
            W, err = eval_model(X_st, y, iterations=iteration, alpha=alfa)
            if err < best[0]:
                best = [err, iteration, alfa]
    print(f'Лучшие параметры iteration={best[1]}, alfa={best[2]} со значением err={best[0]}')

In [10]:
best_param([10000, 50000, 100000, 150000, 200000, 300000], [0.1, 0.01, 0.05, 1e-3, 5e-3, 1e-4, 5e-4, 1e-5])

iteration: 10000, alfa: 0.1
10000 [-11.27241705  -1.45342424  -2.38315559   9.49424167] 0.25238324894935554
iteration: 10000, alfa: 0.01
10000 [-2.77079473 -0.99580928  0.56650766  3.2676589 ] 0.4058305387773311
iteration: 10000, alfa: 0.05
10000 [-7.85466344 -1.19933686 -1.28738111  6.80540153] 0.2931230243955607
iteration: 10000, alfa: 0.001
10000 [-0.29756287 -0.72669083  1.06148576  1.39664388] 0.5233563729128639
iteration: 10000, alfa: 0.005
10000 [-1.53715836 -0.94411088  0.98699727  2.45300573] 0.4534103085773757
iteration: 10000, alfa: 0.0001
10000 [ 0.25808924 -0.68189547  0.68834749  1.2411954 ] 0.5906743816929662
iteration: 10000, alfa: 0.0005
10000 [-0.06997385 -0.68665886  0.94957377  1.2441334 ] 0.5416456771092769
iteration: 10000, alfa: 1e-05
10000 [ 0.45886981 -0.25439705  0.6453131   1.46695998] 1.0393648355410017
iteration: 50000, alfa: 0.1
50000 [-26.07030122  -2.7286846   -6.81038328  21.47869092] 0.15099538645603017
iteration: 50000, alfa: 0.01
50000 [-7.85441079 -

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  


300000 [-56.20163494  -5.26790425 -15.51900064  45.4697445 ] nan
iteration: 300000, alfa: 0.01
300000 [-20.12046178  -2.20554145  -5.06338174  16.65513544] 0.18225133394128198
iteration: 300000, alfa: 0.05
300000 [-42.5800683   -4.1712129  -11.56628057  34.75687729] 0.10108473054739564
iteration: 300000, alfa: 0.001
300000 [-5.90935598 -1.08770924 -0.62102637  5.36106613] 0.3250047511493259
iteration: 300000, alfa: 0.005
300000 [-13.94271361  -1.67368577  -3.20717389  11.64580974] 0.22733631787969824
iteration: 300000, alfa: 0.0001
300000 [-0.95624035 -0.87644457  1.10163265  2.00543623] 0.48128705597746324
iteration: 300000, alfa: 0.0005
300000 [-3.76552928 -1.01496641  0.17888788  3.90129243] 0.3748915448629178
iteration: 300000, alfa: 1e-05
300000 [ 0.06280227 -0.6861149   0.85151128  1.21295643] 0.5559828664575782
Лучшие параметры iteration=200000, alfa=0.1 со значением err=0.09156004715343113


In [11]:
W, err = eval_model(X_st, y, iterations=200000, alpha=0.1)

200000 [-47.83523093  -4.60958703 -13.08107424  38.92379106] 0.09156004715343113


#### 3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [12]:
def calc_pred_proba(W, X):
    z = np.dot(W, X)
    y_pred = sigmoid(z)
    return y_pred

In [13]:
calc_pred_proba(W, X_st)

array([0.33027502, 0.00223262, 1.        , 0.03215065, 0.96673777,
       0.01491352, 1.        , 0.00807259, 0.65518501, 1.        ])

#### 4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [14]:
def calc_pred(W, X):
    z = np.dot(W, X)
    y_pred = sigmoid(z)
    return np.around(y_pred)

In [15]:
y_pred = calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

#### 5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [23]:
accuracy = sum(y == y_pred) / len(y_pred)
accuracy

1.0

In [17]:
def matrix(y, y_pred):
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for idx, val in enumerate(y_pred):
        if val == 1 and y[idx] == 1:
            TP += 1
        if val == 1 and y[idx] == 0:
            FP += 1
        if val == 0 and y[idx] == 0:
            TN += 1
        if val == 0 and y[idx] == 1:
            FN += 1
    return TP, TN, FP, FN

In [18]:
TP, TN, FP, FN = matrix(y, y_pred)
print(TP, TN, FP, FN)

5 5 0 0


In [19]:
accuracy = (TP + TN) / len(y_pred)
accuracy

1.0

In [20]:
precision = TP / TP + FP
precision

1.0

In [21]:
recall = TP / TP + FN
recall

1.0

In [22]:
F1 = 2 * precision * recall / (precision + recall)
F1

1.0

#### 6. Могла ли модель переобучиться? Почему?

Могла. Так как было очень много итераций.